### ISSUE TITLE
Dependency on a non-existent service `profiler'

### ISSUE THREAD

**Issue by tlode** [pomm-project/pomm-bundle#13]
When running in prod environment, I get this error message 

```Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'The service "pomm.controller.profiler" has a dependency on a non-existent service "profiler"```

Could it be that the service `pomm.controller.profiler` should reference `@profiler` as an optional argument in `pomm-bundle/sources/lib/Resources/config/services.yml`?

```yml
pomm.controller.profiler:
        class: "PommProject\\SymfonyBridge\\Controller\\PommProfilerController"
        arguments: ['@router', '@?profiler', '@twig', '@pomm']
```

I don't know if this would be the right solution, I am just getting started with symfony.
