### ISSUE TITLE
BaseGenerator::__construct() must be an instance of PommProject\ModelManager\Session

### ISSUE THREAD

**Issue by GromNaN** [pomm-project/pomm-bundle#38]
I'm trying to install the PommBundle (latest version). 

Here is my config:
```yaml
pomm:
    configuration:
        redshift:
            dsn: 'pgsql://%redshift.username%:%redshift.password%@%redshift.host%:5439/%redshift.database%'
    logger:
        service: '@logger'
```

When running the following command I get an exception:

```
php console pomm:generate:relation-all -d src/ -a 'PublicationBundle\Model' redshift client
```

```
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to PommProject\ModelManager\Generator\BaseGenerator::__construct() must be an instance of PommProject\ModelManager\Session, 
  instance of PommProject\Foundation\Session given, called in vendor/pomm-project/cli/sources/lib/Command/GenerateForRelation.php on line 76 and defined
```

Is there something to configure for the `class:session_builder` ? This config is in the Configuration class, but I don't find the expected value.

**Comment by webaaz** [comment]
It's a known bug since the last version of the model manager. We're working on a fix. /ping @sanpii @chanmix51

**Comment by sanpii** [comment]
> Is there something to configure for the class:session_builder ?

Yes, as you can see in the [README](https://github.com/pomm-project/pomm-bundle#configuration):

```yaml
        redshift:
            dsn: 'pgsql://%redshift.username%:%redshift.password%@%redshift.host%:5439/%redshift.database%'
            class:session_builder: '\PommProject\ModelManager\SessionBuilder'
```
